backend:
  name: git-gateway
  branch: main
media_folder: public/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "content/home.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - { label: "Mission Title", name: "title_mission", widget: "string" }
          - { label: "Mission", name: "section_mission", widget: "markdown" }
          - { label: "DEFI Title", name: "title_defi", widget: "string" }
          - { label: "DEFI", name: "section_defi", widget: "markdown" }
